export const STRONG_CAMPAIGN_KEYWORDS = [
  "statement of work",
  "sow",
  "usage rights",
  "whitelisting",
  "creator partnership",
  "brand deal",
  "paid partnership",
  "sponsorship",
  "creative brief",
  "campaign brief",
  "influencer campaign",
  "contract",
  "agreement",
];

export const CAMPAIGN_KEYWORDS = [
  "campaign",
  "brief",
  "proposal",
  "deliverables",
  "ugc",
  "influencer",
  "collab",
  "collaboration",
  "content creator",
  "rate",
  "budget",
  "fee",
  "compensation",
  "payment",
  "timeline",
  "go live",
  "posting",
  "deliverable",
];

export const NEGATIVE_KEYWORDS = [
  "password reset",
  "verification code",
  "security alert",
  "newsletter",
  "unsubscribe",
  "receipt",
  "order confirmation",
  "shipping",
  "tracking",
  "login",
  "support ticket",
  "job application",
  "careers",
  "webinar",
];
